Adapted from code for data extraction for work on overabundance in Latin

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import re
import math

# Working on LASLA tokens

In [2]:
lasla_tokens_UDset = pd.read_csv("query_lasla_tokens_UDset.csv")

In [3]:
def remove_non_numeric(lemma):
    lemma = float(re.sub("[^0-9]","",lemma))
    return(lemma)

In [4]:
lasla_tokens_UDset["lila_id_lemma_float"] = lasla_tokens_UDset["lila_id_lemma"].map(remove_non_numeric)

obtaining frequencies of forms in LASLA

In [5]:
lasla_tokens_UDset["token-lemma-UD"] = lasla_tokens_UDset["tokenLabel"] + lasla_tokens_UDset["lila_id_lemma_float"].astype(str) + lasla_tokens_UDset["UD_features"]

In [6]:
frequencies = lasla_tokens_UDset["token-lemma-UD"].value_counts()

In [7]:
frequencies_dict = {'frequency': frequencies}

In [8]:
frequencies_df = pd.DataFrame(frequencies_dict)

In [9]:
lasla_forms_freq = lasla_tokens_UDset.drop_duplicates(subset=["token-lemma-UD"]).drop(columns=["token"]).set_index("token-lemma-UD")

In [10]:
for i in tqdm(lasla_forms_freq.index):
    lasla_forms_freq.loc[i,"frequency"] = frequencies_df.loc[i,"frequency"]

100%|█████████████████████████████████████████████████████████████████████████| 72493/72493 [00:03<00:00, 18130.43it/s]

In [11]:
lasla_forms_freq = lasla_forms_freq.sort_values(by=["frequency"], ascending=False).reset_index()

obtaing variant group for each form

# Mapping UD features of LASLA to cells in paralex format of PrinParLat

In [12]:
UD_features = lasla_forms_freq.copy()

In [13]:
UD_features = UD_features.drop_duplicates(subset=["UD_features"]).reset_index()

In [14]:
for col in UD_features:
    if col not in [ "UD_features" , "tokenLabel" , "cell"] :
        UD_features = UD_features.drop(columns = col)

In [15]:
for i in UD_features.index:
    #print(i)
    featureValue_list = UD_features.loc[i,"UD_features"].split("; ")
    #print(featureValue_list)
    for featureValue in featureValue_list:
        feature = re.sub("(https://universaldependencies.org/la/feat/|#.+)","",featureValue)
        feature = re.sub("#.+","",feature)
        value = re.sub("^.+#","",featureValue)
        #print(feature,value)
        UD_features.loc[i,feature] = value

C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Imp' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'LatAnom' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Ind' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Sing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Pres' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Fin' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Ind' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Act' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Voc' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Pos' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Masc' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1022588719.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Yes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  UD_features.loc[i,feature] = value

In [16]:
UD_features = UD_features.drop(columns=["Degree","InflClass","InflClass%5Bnominal%5D"])

In [17]:
col_list=list()
for col in UD_features:
    if col != "UD_features":
        col_list.append(col)

#UD_features.drop_duplicates(subset = col_list)

In [18]:
UD_features["Tense-Aspect"] = UD_features["Tense"].astype(str) + UD_features["Aspect"].astype(str)

In [19]:
UD_features["cell_mapped"] = ""

mapping single UD features to paralex format wherever possible

In [20]:
mapping = {
    "FutImp" : "fut.",
    "FutPerf" : "fprf.",
    "nanImp" : "nanImp.",
    "nannan" : "nannan.",
    "nanPerf" : "prf.",
    "nanProsp" : "nanProsp.",
    "PastImp" : "iprf.",
    "PastPerf" : "prf.",
    "PqpPerf" : "pprf.",
    "PresImp" : "prs.",
    "Act": "act.",
    "Pass": "pass.",
    "Fin": "",
    "Gdv": "gdv.",
    "Ger": "ger.",
    "Inf": "inf.",
    "Part": "ptcp.",
    "Sup": "sup.",
    "Ind": "ind.",
    "Sub": "sbjv.",
    "Imp": "imp.",
    "Nom": "nom.",
    "Gen": "gen.",
    "Dat": "dat.",
    "Acc": "acc.",
    "Voc": "voc.",
    "Abl": "abl.",
    "Masc": "m.",
    "Fem": "f.",
    "Neut": "n.",
    "Fem,Masc": "f/m.",
    "Fem,Masc,Neut": "f/m/n.",
    "Masc,Neut": "m/n.",
    "1": "1.",
    "2": "2.",
    "3": "3.",
    "Sing": "sg",
    "Plur": "pl"
}

for i in UD_features.index:
    for feature in ["Tense-Aspect" , "Voice" , "VerbForm", "Mood", "Case" , "Gender", "Person" , "Number"]:
        value = UD_features.loc[i,feature]
        if value in mapping:
            paralex = mapping[value]
            UD_features.loc[i,"cell_mapped"] = UD_features.loc[i,"cell_mapped"] + paralex

Some automatic post-hoc refining

In [21]:
for i in UD_features.index:
    cell_mapped = UD_features.loc[i,"cell_mapped"]
    if "nanImp." in cell_mapped:
        #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
        if UD_features.loc[i,"VerbForm"] == "Inf":
            if type(UD_features.loc[i,"Case"]) is float:
                cell_mapped = re.sub("nanImp\.","prs.",cell_mapped)
            else:
                cell_mapped = re.sub("nanImp\.","fut.",cell_mapped)
                cell_mapped = re.sub("inf.","ptcp.",cell_mapped)
        else:
            cell_mapped = re.sub("nanImp\.","prs.",cell_mapped)
        print(cell_mapped)
    if "nannan." in cell_mapped:
        #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
        cell_mapped = re.sub("nannan.","",cell_mapped)
        #print(cell_mapped)
    if "nanProsp" in cell_mapped:
        #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
        #print(UD_features.loc[i,"VerbForm"],type(UD_features.loc[i,"Case"]))
        if UD_features.loc[i,"VerbForm"] == "Ger":
            #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
            cell_mapped = re.sub("nanProsp\.pass\.","",cell_mapped)
            cell_mapped = re.sub("\.(n\.)?sg","",cell_mapped)
            #print(cell_mapped)
        elif UD_features.loc[i,"VerbForm"] == "Gdv":
            #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
            cell_mapped = re.sub("nanProsp\.pass\.","",cell_mapped)
            #print(cell_mapped)
        elif UD_features.loc[i,"VerbForm"] == "Sup":
            #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
            cell_mapped = re.sub("nanProsp\.","",cell_mapped)
            #print(cell_mapped)
        elif UD_features.loc[i,"VerbForm"] == "Part":
                if re.match(".+ur(us|a|um|i|ae|o|a|am|e|orum|arum|is|os|as)$", UD_features.loc[i,"tokenLabel"]):
                    #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
                    cell_mapped = re.sub("nanProsp\.","fut.",cell_mapped)
                    #print(cell_mapped)
                else:
                    #print(cell_mapped,UD_features.loc[i,"tokenLabel"])
                    cell_mapped = cell_mapped + "???"
                    #print(cell_mapped)
    else:
            print(cell_mapped,UD_features.loc[i,"tokenLabel"])
    UD_features.loc[i,"cell_mapped"] = re.sub("\.$","",cell_mapped)

prs.ind.3.sg est
prs.inf.
prs.inf. esse
prs.ind.3.pl sunt
prs.sbjv.3.sg sit
iprf.ind.3.sg erat
prf.ind.3.sg fuit
iprf.sbjv.3.sg esset
prs.act.ind.3.sg potest
fut.ind.3.sg erit
prs.act.inf.
prs.act.inf. posse
prs.act.ind.3.sg habet
prs.act.inf.
prs.act.inf. facere
prs.act.inf.
prs.act.inf. dicere
prf.inf. fuisse
iprf.ind.3.pl erant
prs.sbjv.3.pl sint
prs.ind.1.sg sum
prs.act.sbjv.3.sg possit
prs.ind.2.sg es
iprf.act.sbjv.3.sg posset
prs.act.inf.
prs.act.inf. habere
prf.act.ind.3.sg dedit
prf.act.ind.3.sg fecit
prf.act.ind.3.sg dixit
prs.act.ind.3.sg facit
prs.pass.ind.3.sg uidetur
iprf.sbjv.3.pl essent
prs.act.inf.
prs.act.inf. dare
prf.act.ind.3.sg potuit
prf.act.ind.3.sg iussit
prs.act.ind.1.sg dico
prs.act.ind.3.pl possunt
prs.act.ind.2.sg uis
prf.sbjv.3.sg fuerit
prf.act.ind.3.sg uenit
prs.act.ind.3.pl habent
prs.act.ind.3.sg uenit
prf.act.ind.1.sg dixi
prs.ind.1.pl sumus
prs.act.ind.1.sg possum
iprf.act.sbjv.3.pl possent
pprf.sbjv.3.sg fuisset
iprf.act.ind.3.sg poterat
prs.act.ind.1.sg uideo
fut.act.ind.1.sg dicam
prs.act.ind.1.sg nescio
prs.act.imp.2.sg uale
iprf.pass.sbjv.3.sg uideretur
prs.act.inf.
prs.act.inf. scire
prs.pass.sbjv.3.sg uideatur
prs.act.ind.2.sg uides
prs.pass.inf.
prs.pass.inf. uideri
prf.ind.3.pl fuerunt
prs.act.sbjv.2.sg possis
prs.act.ind.3.sg dat
prs.sbjv.2.sg sis
prf.act.ind.1.sg uidi
prs.pass.inf.
prs.pass.inf. uti
prs.pass.ind.3.sg dicitur
iprf.pass.ind.3.sg uidebatur
prs.act.ind.2.sg putas
prf.pass.ptcp.voc.m.pl conscripti
fut.sbjv.3.sg foret
pprf.ind.3.sg fuerat
iprf.act.ind.3.sg habebat
fut.ind.3.pl erunt
prf.pass.ptcp.nom.n.sg factum
prs.act.sbjv.3.sg habeat
prs.act.sbjv.1.sg dicam
prs.act.sbjv.3.pl possint
prs.act.ind.3.sg dicit
prf.pass.ptcp.nom.m.sg factus
iprf.act.sbjv.3.sg haberet
prs.act.ind.3.pl faciunt
prf.act.inf. fecisse
prs.pass.ind.3.pl uidentur
prs.pass.inf.
prs.pass.inf. pati
prf.pass.ptcp.nom.f.sg facta
prs.act.ind.2.sg quaeris
prf.pass.ptcp.nom.m.sg ausus
fut.act.imp.2.sg facito
prf.pass.ptcp.acc.m/n.sg factum
prs.act.imp.2.sg dic
prs.pass.ind.1.sg opinor
prs.act.ind.1.sg puto
iprf.act.sbjv.3.sg diceret
prs.pass.ind.3.sg datur
fut.act.ind.3.sg dabit
prs.act.ind.1.pl uidemus
prs.act.sbjv.3.sg faciat
fut.ind.2.sg eris
prf.act.ind.1.sg feci
prf.act.ind.3.pl coeperunt
prs.act.ind.1.pl possumus
prs.act.ind.2.pl uidetis
fut.act.ind.2.sg uoles
prf.act.inf. potuisse
fut.act.ind.3.sg poterit
prf.pass.ptcp.nom.m.sg natus
prs.act.sbjv.3.sg dicat
prs.act.ind.3.pl dicunt
prs.pass.inf.
prs.pass.inf. dari
prs.pass.ind.3.sg fertur
prs.sbjv.1.sg sim
fut.act.ind.1.sg faciam
iprf.act.sbjv.3.sg faceret
iprf.act.ind.3.pl poterant
prf.ind.1.sg fui
prs.act.imp.2.sg da
prs.act.imp.2.sg fac
prs.act.sbjv.1.sg possim
prs.pass.ind.1.sg uideor
prs.act.ind.2.sg facis
fut.act.ind.1.sg dabo
pprf.act.sbjv.3.sg uenisset
prs.act.sbjv.2.sg putes
fut.act.ind.3.sg faciet
prf.act.inf. uenisse
prs.pass.sbjv.3.pl uideantur
prs.pass.ind.3.sg patitur
prs.act.sbjv.2.sg facias
pprf.act.sbjv.3.sg potuisset
prs.act.ind.2.sg scis
prf.pass.ptcp.nom.n.sg datum
prs.act.ind.3.pl putant
iprf.sbjv.1.sg essem
iprf.act.ind.3.sg dicebat
fut.act.ind.3.sg dicet
pprf.act.ind.3.sg fecerat
iprf.act.sbjv.3.sg daret
prf.act.sbjv.3.sg fecerit
prf.pass.ptcp.nom.f.sg data
prf.act.inf. dedisse
prf.pass.ptcp.abl.m/n.sg facto
prs.act.ind.1.pl dicimus
prf.act.ind.1.sg dedi
prf.act.ind.3.pl uoluerunt
prs.act.sbjv.2.sg scias
prf.act.inf. dixisse
prs.pass.ind.1.sg loquor
prs.act.sbjv.3.sg putet
prf.pass.ptcp.nom.n.sg uisum
pprf.act.sbjv.3.sg fecisset
iprf.act.sbjv.1.sg uellem
prs.act.sbjv.3.sg ueniat
prs.act.ind.3.pl ueniunt
prf.pass.ptcp.nom.n.pl facta
prf.pass.ptcp.abl.f/m/n.pl relictis
pprf.act.ind.3.sg uenerat
pprf.act.ind.3.sg dixerat
iprf.act.ind.3.sg dabat
iprf.ind.1.sg eram
prs.act.imp.2.sg i
prf.pass.ptcp.nom.f.sg uisa
prf.pass.ptcp.nom.n.sg dictum
iprf.sbjv.2.sg esses
prf.act.ind.1.sg potui
prf.pass.ptcp.nom.n.sg uentum
prs.act.ind.1.sg facio
prf.pass.ptcp.nom.m.pl secuti
prf.pass.ptcp.abl.f.sg cognita
prf.act.ind.1.pl uidimus
fut.act.ind.2.sg dices
prs.act.imp.2.pl ite
prf.pass.ptcp.abl.m/n.sg dato
prs.pass.inf.
prs.pass.inf. ferri
prs.act.ind.2.pl putatis
prf.sbjv.3.pl fuerint
pprf.sbjv.3.pl fuissent
prf.act.ind.2.sg fecisti
iprf.act.sbjv.3.pl facerent
fut.ind.1.sg ero
pprf.ind.3.pl fuerant
prs.act.sbjv.2.sg dicas
prf.act.inf. habuisse
fut.act.ind.3.sg licebit
fut.act.ind.3.sg ueniet
prs.act.imp.2.pl cognoscite
iprf.ind.2.sg eras
pprf.act.sbjv.3.sg dixisset
prs.act.sbjv.3.pl habeant
prs.act.imp.2.pl uidete
iprf.act.ind.3.pl habebant
prs.pass.ind.3.pl dicuntur
prs.act.sbjv.1.sg faciam
iprf.pass.ind.3.pl uidebantur
prs.ind.2.pl estis
iprf.act.sbjv.2.sg posses
fut.sbjv.3.pl forent
prf.pass.ptcp.abl.m/n.sg relicto
fprf.ind.3.sg fuerit
prs.act.sbjv.3.pl faciant
fut.act.ind.2.sg uidebis
prf.pass.ptcp.acc.m/n.sg datum
prf.pass.ptcp.abl.f.sg facta
pprf.act.ind.3.sg dederat
prf.act.ind.3.pl uenerunt
fut.act.ind.2.sg inuenies
prf.act.ind.3.pl dixerunt
iprf.pass.sbjv.3.pl uiderentur
prf.act.ind.2.pl audistis
prf.act.ind.2.sg dixisti
iprf.act.sbjv.3.pl haberent
iprf.pass.ind.3.sg arbitrabatur
fut.act.ind.2.sg facies
prf.act.sbjv.3.sg dixerit
prf.act.ind.1.pl accepimus
prf.pass.ptcp.nom.m.sg conatus
prs.act.ind.2.pl potestis
iprf.act.sbjv.3.pl dicerent
prs.pass.sbjv.3.sg detur
prf.pass.ptcp.nom.n.pl data
prf.pass.ptcp.nom.f.sg uicta
prs.act.imp.2.pl date
prf.pass.ptcp.acc.f.sg factam
prf.act.ind.1.pl diximus
prf.act.ind.3.pl dederunt
prf.act.ind.1.sg audiui
fut.imp.3.sg esto
prs.pass.inf.
prs.pass.inf. experiri
fut.act.ind.1.sg ibo
prf.ind.2.sg fuisti
prs.act.sbjv.2.sg habeas
prs.pass.ind.3.pl feruntur
prs.pass.ind.3.pl arbitrantur
prs.act.sbjv.1.sg putem
prf.pass.ptcp.abl.f/m/n.pl interfectis
prs.act.sbjv.1.pl possimus
iprf.act.sbjv.1.sg dicerem
fut.act.ind.2.sg dabis
prf.pass.ptcp.nom.m.sg expertus
prs.sbjv.1.pl simus
prf.pass.ptcp.acc.f.sg datam
pprf.act.ind.3.sg iusserat
prs.pass.sbjv.1.sg uidear
prf.act.ind.2.sg uoluisti
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg ferens
iprf.pass.ind.3.pl sequebantur
prf.act.ind.2.sg dedisti
pprf.act.sbjv.3.sg dedisset
prs.act.sbjv.1.pl uideamus
prf.pass.ptcp.nom.n.pl dicta
iprf.pass.sbjv.3.sg uteretur
prf.pass.ptcp.dat.f/m/n.pl uictis
iprf.pass.sbjv.3.sg daretur
prs.pass.sbjv.3.sg sequatur
iprf.act.sbjv.3.sg ueniret
prf.act.sbjv.3.sg potuerit
iprf.act.ind.3.sg faciebat
prf.pass.ptcp.acc.m/n.sg natum
prf.pass.ptcp.acc.m.pl uictos
prf.act.ind.3.pl uiderunt
prs.act.ind.1.pl damus
prf.pass.ptcp.acc.n.pl facta
fut.act.ind.3.pl poterunt
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg fugiens
prs.pass.imp.2.sg sequere
pprf.act.sbjv.3.pl fecissent
fut.act.imp.2.sg indito
fut.pass.ind.3.sg dabitur
iprf.act.ind.3.pl dicebant
prf.act.sbjv.1.sg dixerim
prs.act.sbjv.3.pl dicant
pprf.act.sbjv.3.sg uidisset
prf.pass.ptcp.nom.m.pl iussi
prf.pass.ptcp.abl.f/m/n.pl datis
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg metuens
prf.sbjv.2.sg fueris
prf.pass.ptcp.nom.f.sg orta
fut.act.imp.2.sg dato
iprf.act.sbjv.2.sg diceres
prs.pass.ind.3.sg oritur
prs.pass.ind.3.pl patiuntur
prf.pass.ptcp.nom.m.pl capti
prs.act.ind.1.pl scimus
iprf.act.sbjv.1.pl possemus
prs.act.sbjv.1.sg debeam
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg absentem
pprf.act.ind.3.pl fecerant
pprf.act.sbjv.3.pl potuissent
prs.pass.sbjv.1.sg loquar
prs.act.sbjv.2.pl possitis
pprf.act.sbjv.3.pl uenissent
prf.act.sbjv.3.sg dederit
fut.pass.ind.3.sg uidebitur
iprf.pass.ind.3.pl arbitrabantur
iprf.act.sbjv.1.sg putarem
iprf.act.sbjv.2.sg uideres
pprf.act.ind.3.pl uenerant
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg absente
prs.act.imp.2.sg ueni
prf.pass.ptcp.abl.f.sg data
prs.act.sbjv.3.pl ueniant
prf.act.ind.1.pl demonstrauimus
iprf.pass.sbjv.3.sg pateretur
prf.act.sbjv.3.sg uenerit
prf.act.sbjv.2.sg feceris
fut.imp.2.sg esto
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg sedens
prs.act.sbjv.3.pl dent
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg iacentem
iprf.act.sbjv.2.sg putares
prs.act.ind.1.pl facimus
prs.act.imp.2.pl audite
prs.act.ind.2.pl dicitis
prf.act.ind.2.pl uidistis
iprf.act.ind.3.sg sciebat
fut.act.ind.3.pl facient
prs.act.ind.2.pl scitis
prf.pass.ptcp.abl.m/n.sg audito
fprf.act.ind.3.sg uenerit
iprf.act.sbjv.1.sg facerem
iprf.act.sbjv.1.pl haberemus
iprf.pass.ind.3.sg ferebatur
iprf.act.ind.3.pl stabant
prs.act.sbjv.2.pl putetis
prs.act.sbjv.1.sg sciam
fut.act.ind.3.pl dabunt
iprf.pass.ind.3.sg sequebatur
fut.pass.ind.1.sg patiar
prs.pass.sbjv.1.pl uideamur
iprf.act.sbjv.3.pl darent
prf.pass.ptcp.acc.n.pl data
prf.act.sbjv.3.sg uiderit
fut.pass.ind.1.sg sequar
fprf.act.ind.3.sg fecerit
prf.pass.ptcp.acc.m/n.sg solitum
fprf.act.ind.2.sg feceris
iprf.pass.sbjv.3.pl arbitrarentur
prf.pass.ptcp.nom.f.sg lata
fut.ind.1.pl erimus
prf.act.sbjv.3.pl fecerint
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg petenti
fut.act.imp.2.sg scito
prs.pass.imp.2.sg miserere
iprf.act.sbjv.1.sg uiderem
prf.pass.ptcp.acc.m/n.sg uinctum
prf.pass.ptcp.acc.f.pl gestas
prs.pass.sbjv.3.sg patiatur
iprf.act.sbjv.2.sg scires
iprf.act.ind.1.sg uidebam
prf.act.sbjv.2.sg dixeris
prs.pass.ind.2.sg uideris
prf.pass.ptcp.acc.f.sg positam
fut.pass.ind.3.sg sequetur
prs.act.ind.2.pl facitis
fut.act.imp.2.pl scitote
prs.pass.sbjv.3.pl sequantur
prs.pass.ind.1.pl uidemur
prf.pass.ptcp.gen.f.pl gestarum
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg ueniens
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg fugientem
prs.act.sbjv.1.pl faciamus
prf.act.ind.2.sg uidisti
prf.pass.ptcp.nom.n.pl uisa
iprf.act.ind.1.sg poteram
prs.act.sbjv.1.pl dicamus
fprf.act.ind.2.sg dederis
fut.act.imp.2.sg caueto
prf.pass.ptcp.nom.m.pl damnati
fprf.act.ind.2.sg uideris
fprf.act.ind.3.sg dederit
prs.pass.ind.1.pl utimur
prf.pass.ptcp.abl.f.sg audita
fprf.act.ind.1.sg dixero
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg stantem
prf.pass.ptcp.abl.f/m/n.pl remotis
prs.pass.ind.2.sg miraris
iprf.act.ind.1.sg dicebam
fprf.act.ind.3.sg dixerit
fut.act.ind.2.pl reperietis
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg absentis
iprf.act.ind.2.sg poteras
prf.pass.ptcp.acc.m.pl captos
fut.act.ind.1.sg expediam
iprf.act.ind.1.sg putabam
prs.act.sbjv.1.pl demus
prf.pass.ptcp.abl.f/m/n.pl auditis
prf.pass.ptcp.acc.f.pl captas
prf.pass.ptcp.nom.f.pl factae
iprf.pass.sbjv.3.pl sequerentur
prs.act.ptcp.nom.f/m.pl
prs.act.ptcp.nom.f/m.pl flentes
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg uenientem
fut.act.ind.2.pl intellegetis
fut.act.ind.1.sg habebo
iprf.act.sbjv.2.sg faceres
prf.pass.ptcp.abl.m/n.sg uiso
prs.pass.ind.1.sg feror
prf.pass.ptcp.nom.f.pl secutae
fprf.ind.3.pl fuerint
prs.act.imp.2.pl facite
prf.pass.ptcp.nom.m.pl adorti
prs.pass.ind.1.sg patior
prs.pass.ind.2.sg pateris
pprf.sbjv.1.sg fuissem
fut.pass.ind.3.sg reperietur
iprf.act.ind.2.sg solebas
prf.act.ind.2.sg uenisti
prf.ind.1.pl fuimus
prf.act.ind.1.pl uenimus
prf.pass.ptcp.abl.f.sg habita
prs.pass.sbjv.3.pl ferantur
prs.act.ptcp.acc.f/m.pl
prs.act.ptcp.acc.f/m.pl fugientes
prf.pass.ptcp.acc.f.pl datas
prs.act.ptcp.nom.f/m/n.sg
prs.act.ptcp.nom.f/m/n.sg lacrimans
prf.act.ind.2.pl nostis
fut.act.ind.3.pl dicent
prs.pass.ind.2.sg quereris
prf.ind.2.pl fuistis
iprf.pass.sbjv.1.sg uiderer
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl fugientium
prs.pass.sbjv.2.sg fateare
prs.act.ptcp.dat.f/m/n.pl
prs.act.ptcp.dat.f/m/n.pl laborantibus
prs.act.ptcp.abl.f/m/n.pl
prs.act.ptcp.abl.f/m/n.pl inspectantibus
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg audiente
prs.act.sbjv.1.pl ueniamus
fut.act.ind.3.pl habebunt
prs.act.sbjv.2.pl uideatis
prs.pass.sbjv.1.pl sequamur
prf.act.ind.2.pl fecistis
fprf.act.ind.1.sg fecero
fut.act.ind.1.pl uidebimus
prs.act.ptcp.acc.f/m.sg
prs.act.ptcp.acc.f/m.sg agentem
pprf.act.sbjv.1.sg fecissem
prs.pass.ind.1.pl patimur
fut.pass.ind.1.sg fatebor
prf.pass.ptcp.acc.m.pl uinctos
iprf.act.ind.3.pl ueniebant
prs.pass.ind.1.pl miramur
iprf.pass.sbjv.3.pl paterentur
pprf.act.ind.3.pl dederant
prs.pass.sbjv.3.pl patiantur
prs.act.sbjv.2.pl intellegatis
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg absenti
prf.pass.ptcp.acc.n.pl gesta
pprf.act.ind.1.sg dixeram
pprf.act.ind.3.sg tulerat
iprf.act.ind.1.sg sciebam
prf.pass.ptcp.acc.n.pl audita
prs.act.ptcp.dat.f/m/n.pl
prs.act.ptcp.dat.f/m/n.pl fugientibus
pprf.act.ind.3.pl constiterant
fut.act.ind.1.pl dicemus
fut.act.ind.3.pl uenient
pprf.act.sbjv.3.pl dedissent
prf.act.sbjv.3.pl uiderint
prf.pass.ptcp.acc.n.pl mixta
prf.pass.ptcp.acc.m.pl perterritos
prs.pass.sbjv.3.pl arbitrentur
iprf.act.ind.2.sg dicebas
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg dicente
iprf.pass.ind.1.sg uidebar
iprf.act.sbjv.3.pl scirent
prf.pass.ptcp.nom.f.pl datae
prf.pass.ptcp.dat.m/n.sg uicto
prs.pass.imp.2.sg patere
fprf.act.ind.3.sg uiderit
iprf.sbjv.1.pl essemus
prs.pass.imp.2.sg effare
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg uenienti
prs.pass.ind.2.pl arbitramini
prf.act.ind.2.pl potuistis
iprf.act.ind.3.pl faciebant
prf.pass.ptcp.acc.m/n.sg delatum
prs.pass.imp.2.pl recordamini
prf.pass.ptcp.nom.n.pl audita
prs.pass.sbjv.3.sg feratur
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg manente
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl audientium
iprf.pass.ind.1.sg arbitrabar
iprf.pass.sbjv.3.sg experiretur
pprf.act.sbjv.1.sg uenissem
iprf.pass.ind.3.pl ferebantur
prs.pass.ind.1.sg experior
pprf.sbjv.2.sg fuisses
prs.act.ptcp.dat.f/m/n.pl
prs.act.ptcp.dat.f/m/n.pl petentibus
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg stante
prf.pass.ptcp.nom.m.sg elatus
prs.act.ptcp.abl.f/m/n.pl
prs.act.ptcp.abl.f/m/n.pl audientibus
pprf.act.ind.3.pl habuerant
prf.act.sbjv.2.sg dederis
prf.pass.ptcp.nom.n.pl delata
prs.pass.ind.3.pl reperiuntur
prf.act.sbjv.2.sg potueris
fut.pass.ind.3.pl dicentur
fut.act.ind.1.pl dabimus
prf.pass.ptcp.nom.n.sg relatum
fprf.act.ind.3.sg uoluerit
fut.pass.ind.1.sg experiar
prs.sbjv.2.pl sitis
iprf.pass.ind.3.sg patiebatur
pprf.act.sbjv.2.sg potuisses
prs.act.sbjv.2.pl audiatis
prf.act.sbjv.3.pl oderint
fprf.ind.2.sg fueris
fprf.act.ind.2.sg dixeris
prf.pass.ptcp.abl.f.sg oblata
prf.pass.ptcp.acc.m.pl damnatos
prf.act.sbjv.2.sg ueneris
pprf.act.sbjv.3.pl reliquissent
iprf.pass.sbjv.1.sg arbitrarer
iprf.pass.sbjv.3.sg referretur
fut.pass.ind.3.sg patietur
prf.pass.ptcp.gen.f.sg captae
iprf.act.sbjv.1.sg scirem
fut.pass.ind.3.pl uidebuntur
iprf.act.ind.1.pl uidebamus
prf.act.sbjv.3.pl potuerint
iprf.pass.ind.3.sg audiebatur
prs.imp.2.pl este
prf.pass.ptcp.nom.f.pl habitae
prs.pass.sbjv.2.pl patiamini
prs.act.ptcp.nom.f/m.pl
prs.act.ptcp.nom.f/m.pl ducentes
prf.pass.ptcp.dat.m/n.sg mortuo
pprf.act.ind.2.sg dederas
fut.ind.2.pl eritis
prs.pass.sbjv.2.sg patiare
fut.pass.ind.3.pl dabuntur
fprf.ind.1.sg fuero
pprf.act.ind.1.sg audieram
pprf.act.sbjv.1.sg dedissem
prf.act.sbjv.3.pl uenerint
prf.pass.ptcp.gen.m/n.sg mortui
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg roganti
iprf.pass.ind.3.pl patiebantur
fprf.act.ind.1.sg uidero
fut.sbjv.2.sg fores
fprf.act.ind.2.sg uolueris
iprf.act.ind.2.sg putabas
pprf.act.sbjv.1.sg potuissem
prs.pass.sbjv.2.pl uideamini
pprf.act.sbjv.1.sg dixissem
prf.pass.ptcp.acc.f.sg oblatam
prf.pass.ptcp.acc.f.sg habitam
fut.act.ind.1.pl feremus
prs.act.ptcp.acc.f/m.pl
prs.act.ptcp.acc.f/m.pl palantis
pprf.act.ind.1.sg coeperam
pprf.act.ind.3.pl potuerant
fut.pass.ind.2.sg moriere
pprf.ind.1.sg fueram
fut.pass.ind.2.pl patiemini
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg habenti
prs.pass.sbjv.1.sg mirer
prf.pass.ptcp.abl.f/m/n.pl conlatis
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg morientis
prf.sbjv.1.sg fuerim
prs.act.ptcp.dat.f/m/n.sg
prs.act.ptcp.dat.f/m/n.sg cupienti
prs.act.ptcp.abl.f/m/n.pl
prs.act.ptcp.abl.f/m/n.pl absentibus
prs.pass.sbjv.2.sg mireris
prs.pass.sbjv.1.sg ferar
prs.act.ptcp.dat.f/m/n.pl
prs.act.ptcp.dat.f/m/n.pl uenientibus
prf.act.sbjv.2.sg uideris
prs.act.ptcp.acc.f/m.pl
prs.act.ptcp.acc.f/m.pl euntis
pprf.ind.2.sg fueras
prf.pass.ptcp.gen.m/n.sg dati
fut.act.ind.1.pl faciemus
pprf.act.sbjv.3.pl habuissent
prf.pass.ptcp.gen.f.pl captarum
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg uenientis
iprf.pass.sbjv.3.pl circumuenirentur
iprf.pass.sbjv.1.sg paterer
pprf.act.sbjv.2.sg fecisses
prs.pass.sbjv.1.sg patiar
iprf.act.sbjv.2.pl uideretis
prf.pass.ptcp.dat.f/m/n.pl obsessis
fprf.act.ind.1.sg potuero
fut.act.ind.2.pl uidebitis
prf.pass.ptcp.dat.f/m/n.pl captis
prf.pass.ptcp.nom.f.pl latae
prf.pass.ptcp.nom.m.pl elati
prs.act.ptcp.acc.n.pl
prs.act.ptcp.acc.n.pl pendentia
prf.pass.ptcp.gen.m/n.sg amissi
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg dantis
prf.act.sbjv.1.sg dederim
prs.pass.sbjv.1.pl patiamur
prf.pass.ptcp.gen.m/n.pl proscriptorum
prs.pass.imp.2.pl sequimini
iprf.act.sbjv.1.pl faceremus
fut.sbjv.1.sg forem
iprf.pass.sbjv.1.sg uterer
prf.pass.ptcp.dat.f/m/n.pl fatigatis
fut.pass.ind.2.sg miraberis
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg ruentis
prs.act.ptcp.abl.f/m/n.sg
prs.act.ptcp.abl.f/m/n.sg fugiente
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl imminentium
fut.pass.ind.3.pl proferentur
pprf.act.sbjv.2.sg uenisses
prf.act.sbjv.1.sg tulerim
prs.pass.sbjv.3.sg oriatur
pprf.act.ind.1.sg uideram
prf.act.ind.1.pl tulimus
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl pugnantium
prs.act.ptcp.abl.f/m/n.pl
prs.act.ptcp.abl.f/m/n.pl tacentibus
prf.pass.ptcp.acc.f.pl latas
prf.pass.ptcp.acc.f.sg munitam
prs.pass.sbjv.2.sg loquaris
prf.pass.ptcp.gen.f.sg actae
pprf.act.ind.2.sg dixeras
fut.act.ind.2.pl dubitabitis
prs.act.ptcp.dat.f/m/n.pl
prs.act.ptcp.dat.f/m/n.pl intuentibus
prf.act.sbjv.1.pl meminerimus
prs.act.ptcp.nom.f/m.pl
prs.act.ptcp.nom.f/m.pl palantes
prs.pass.sbjv.1.pl miremur
prs.act.sbjv.2.pl faciatis
prf.act.sbjv.3.pl dederint
prs.act.ptcp.acc.f/m.pl
prs.act.ptcp.acc.f/m.pl sequentis
prf.pass.ptcp.acc.f.pl mixtas
iprf.sbjv.2.pl essetis
pprf.act.sbjv.1.sg uidissem
iprf.act.ind.2.sg sciebas
prf.act.sbjv.1.sg fecerim
prs.act.ptcp.acc.f/m.pl
prs.act.ptcp.acc.f/m.pl iacentis
iprf.pass.sbjv.1.pl uteremur
prs.act.ptcp.acc.n.pl
prs.act.ptcp.acc.n.pl labentia
prs.pass.sbjv.3.pl reperiantur
fprf.act.ind.2.sg inueneris
prf.act.ind.2.pl dedistis
prs.act.ptcp.nom.f/m.pl
prs.act.ptcp.nom.f/m.pl fugientes
fut.pass.ind.1.pl patiemur
prs.act.ptcp.abl.f/m/n.pl
prs.act.ptcp.abl.f/m/n.pl defendentibus
fut.act.imp.3.sg dato
iprf.act.sbjv.2.pl possetis
iprf.ind.1.pl eramus
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl sequentium
iprf.act.ind.2.pl uidebatis
prf.pass.ptcp.abl.m/n.sg praeterito
prf.pass.ptcp.nom.f.pl inuentae
fut.pass.ind.1.pl sequemur
fut.pass.ind.3.sg feretur
prf.pass.ptcp.m. c.
prs.act.ptcp.acc.n.pl
prs.act.ptcp.acc.n.pl obstantia
iprf.act.ind.1.pl poteramus
fut.act.imp.2.sg nolito
pprf.act.ind.2.sg debueras
fprf.act.ind.3.pl fecerint
prs.act.ptcp.nom.f/m.pl
prs.act.ptcp.nom.f/m.pl absentes
prf.pass.sbjv.1.sg ausim
fut.imp.3.pl sunto
prs.pass.imp.2.sg metire
prf.sbjv.2.pl fueritis
iprf.act.sbjv.1.pl putaremus
prs.act.ptcp.gen.f/m/n.sg
prs.act.ptcp.gen.f/m/n.sg iacentis
pprf.act.ind.1.sg dederam
prs.act.ptcp.acc.n.pl
prs.act.ptcp.acc.n.pl fugientia
fut.pass.ind.1.sg ferar
prs.pass.sbjv.1.sg mentiar
pprf.act.sbjv.2.sg dedisses
fut.act.ind.2.pl poteritis
prf.pass.ptcp.gen.m/n.pl damnatorum
fut.act.imp.2.pl mementote
fut.pass.ind.1.sg morabor
iprf.act.ind.1.sg cupiebam
fut.pass.ind.3.pl reperientur
iprf.pass.ind.1.sg querebar
pprf.act.sbjv.2.sg dixisses
fut.act.ind.1.pl inueniemus
fprf.act.ind.3.pl uenerint
prs.pass.ind.2.pl uidemini
prf.pass.ptcp.voc.m.sg nate
iprf.act.sbjv.2.pl putaretis
fut.pass.ind.2.sg uideberis
fut.act.imp.2.pl putatote
prs.imp.2.sg es
iprf.act.sbjv.1.pl ueniremus
prf.act.sbjv.1.sg senserim
fprf.act.ind.1.sg dedero
fprf.act.ind.3.pl uiderint
pprf.act.ind.2.sg audieras
prs.pass.sbjv.2.sg metiaris
iprf.pass.ind.2.sg arbitrabare
iprf.pass.ind.3.pl moliebantur
iprf.pass.sbjv.1.pl uideremur
fprf.act.ind.3.pl dederint
fut.act.imp.3.sg facito
prs.pass.sbjv.2.pl miremini
iprf.act.sbjv.1.pl quaereremus
fut.pass.ind.2.sg experiere
fut.pass.ind.2.sg sequeris
prs.act.ptcp.gen.f/m/n.pl
prs.act.ptcp.gen.f/m/n.pl coeuntium
prs.act.ptcp.dat.f/m/n.pl

<>:7: SyntaxWarning: invalid escape sequence '\.'
<>:9: SyntaxWarning: invalid escape sequence '\.'
<>:12: SyntaxWarning: invalid escape sequence '\.'
<>:23: SyntaxWarning: invalid escape sequence '\.'
<>:24: SyntaxWarning: invalid escape sequence '\.'
<>:28: SyntaxWarning: invalid escape sequence '\.'
<>:32: SyntaxWarning: invalid escape sequence '\.'
<>:37: SyntaxWarning: invalid escape sequence '\.'
<>:45: SyntaxWarning: invalid escape sequence '\.'
<>:7: SyntaxWarning: invalid escape sequence '\.'
<>:9: SyntaxWarning: invalid escape sequence '\.'
<>:12: SyntaxWarning: invalid escape sequence '\.'
<>:23: SyntaxWarning: invalid escape sequence '\.'
<>:24: SyntaxWarning: invalid escape sequence '\.'
<>:28: SyntaxWarning: invalid escape sequence '\.'
<>:32: SyntaxWarning: invalid escape sequence '\.'
<>:37: SyntaxWarning: invalid escape sequence '\.'
<>:45: SyntaxWarning: invalid escape sequence '\.'
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:7: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanImp\.","prs.",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:9: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanImp\.","fut.",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:12: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanImp\.","prs.",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:23: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanProsp\.pass\.","",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:24: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("\.(n\.)?sg","",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:28: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanProsp\.pass\.","",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:32: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanProsp\.","",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:37: SyntaxWarning: invalid escape sequence '\.'
  cell_mapped = re.sub("nanProsp\.","fut.",cell_mapped)
C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1441164272.py:45: SyntaxWarning: invalid escape sequence '\.'
  UD_features.loc[i,"cell_mapped"] = re.sub("\.$","",cell_mapped)

manually established post-hoc corrections

In [22]:
postHoc_corr = {
"fprf.ind.1.pl" : "fprf.act.ind.1.pl" ,
"fprf.ind.1.sg" : "fprf.act.ind.1.sg" ,
"fprf.ind.2.pl" : "fprf.act.ind.2.pl" ,
"fprf.ind.2.sg" : "fprf.act.ind.2.sg" ,
"fprf.ind.3.pl" : "fprf.act.ind.3.pl" ,
"fprf.ind.3.sg" : "fprf.act.ind.3.sg" ,
"pprf.ind.1.pl" : "pprf.act.ind.1.pl" ,
"pprf.ind.1.sg" : "pprf.act.ind.1.sg" ,
"pprf.ind.2.pl" : "pprf.act.ind.2.pl" ,
"pprf.ind.2.sg" : "pprf.act.ind.2.sg" ,
"pprf.ind.3.pl" : "pprf.act.ind.3.pl" ,
"pprf.ind.3.sg" : "pprf.act.ind.3.sg" ,
"pprf.sbjv.1.pl" : "pprf.act.sbjv.1.pl" ,
"pprf.sbjv.1.sg" : "pprf.act.sbjv.1.sg" ,
"pprf.sbjv.2.sg" : "pprf.act.sbjv.2.sg" ,
"pprf.sbjv.3.pl" : "pprf.act.sbjv.3.pl" ,
"pprf.sbjv.3.sg" : "pprf.act.sbjv.3.sg" ,
"prf.ind.1.pl" : "prf.act.ind.1.pl" ,
"prf.ind.1.sg" : "prf.act.ind.1.sg" ,
"prf.ind.2.pl" : "prf.act.ind.2.pl" ,
"prf.ind.2.sg" : "prf.act.ind.2.sg" ,
"prf.ind.3.pl" : "prf.act.ind.3.pl" ,
"prf.ind.3.sg" : "prf.act.ind.3.sg" ,
"prf.inf" : "prf.act.inf" ,
"prf.sbjv.1.pl" : "prf.act.sbjv.1.pl" ,
"prf.sbjv.1.sg" : "prf.act.sbjv.1.sg" ,
"prf.sbjv.2.pl" : "prf.act.sbjv.2.pl" ,
"prf.sbjv.2.sg" : "prf.act.sbjv.2.sg" ,
"prf.sbjv.3.pl" : "prf.act.sbjv.3.pl" ,
"prf.sbjv.3.sg" : "prf.act.sbjv.3.sg" ,
"fut.ptcp.nom.f.sg" : "fut.act.ptcp.nom.f.sg" ,
"fut.ptcp.nom.n.pl" : "fut.act.ptcp.nom.n.pl" ,
"fut.ptcp.acc.n.pl" : "fut.act.ptcp.acc.n.pl" ,
"fut.ptcp.nom.f.pl" : "fut.act.ptcp.nom.f.pl" ,
"fut.ptcp.gen.f.sg" : "fut.act.ptcp.gen.f.sg" ,
"fut.ptcp.acc.f.sg" : "fut.act.ptcp.acc.f.sg" ,
"fut.ptcp.acc.f.pl" : "fut.act.ptcp.acc.f.pl" ,
"fut.ptcp.voc.m.sg" : "fut.act.ptcp.voc.m.sg" ,
"fut.ptcp.nom.m.pl" : "fut.act.ptcp.nom.m.pl" ,
"fut.ptcp.acc.m.pl" : "fut.act.ptcp.acc.m.pl" ,
"fut.ptcp.nom.n.sg" : "fut.act.ptcp.nom.n.sg" ,
"fut.ptcp.nom.m.sg" : "fut.act.ptcp.nom.m.sg" ,
"fut.imp.2.pl" : "fut.act.imp.2.pl" ,
"fut.imp.2.sg" : "fut.act.imp.2.sg" ,
"fut.imp.3.pl" : "fut.act.imp.3.pl" ,
"fut.imp.3.sg" : "fut.act.imp.3.sg" ,
"fut.ind.1.pl" : "fut.act.ind.1.pl" ,
"fut.ind.1.sg" : "fut.act.ind.1.sg" ,
"fut.ind.2.pl" : "fut.act.ind.2.pl" ,
"fut.ind.2.sg" : "fut.act.ind.2.sg" ,
"fut.ind.3.pl" : "fut.act.ind.3.pl" ,
"fut.ind.3.sg" : "fut.act.ind.3.sg" ,
"iprf.ind.1.pl" : "iprf.act.ind.1.pl" ,
"iprf.ind.1.sg" : "iprf.act.ind.1.sg" ,
"iprf.ind.2.pl" : "iprf.act.ind.2.pl" ,
"iprf.ind.2.sg" : "iprf.act.ind.2.sg" ,
"iprf.ind.3.pl" : "iprf.act.ind.3.pl" ,
"iprf.ind.3.sg" : "iprf.act.ind.3.sg" ,
"iprf.sbjv.1.pl" : "iprf.act.sbjv.1.pl" ,
"iprf.sbjv.1.sg" : "iprf.act.sbjv.1.sg" ,
"iprf.sbjv.2.pl" : "iprf.act.sbjv.2.pl" ,
"iprf.sbjv.2.sg" : "iprf.act.sbjv.2.sg" ,
"iprf.sbjv.3.pl" : "iprf.act.sbjv.3.pl" ,
"iprf.sbjv.3.sg" : "iprf.act.sbjv.3.sg" ,
"prs.imp.2.pl" : "prs.act.imp.2.pl" ,
"prs.imp.2.sg" : "prs.act.imp.2.sg" ,
"prs.imp.3.sg" : "prs.act.imp.3.sg" ,
"prs.ind.1.pl" : "prs.act.ind.1.pl" ,
"prs.ind.1.sg" : "prs.act.ind.1.sg" ,
"prs.ind.2.pl" : "prs.act.ind.2.pl" ,
"prs.ind.2.sg" : "prs.act.ind.2.sg" ,
"prs.ind.3.pl" : "prs.act.ind.3.pl" ,
"prs.ind.3.sg" : "prs.act.ind.3.sg" ,
"prs.inf" : "prs.act.inf" ,
"prs.sbjv.1.pl" : "prs.act.sbjv.1.pl" ,
"prs.sbjv.1.sg" : "prs.act.sbjv.1.sg" ,
"prs.sbjv.2.pl" : "prs.act.sbjv.2.pl" ,
"prs.sbjv.2.sg" : "prs.act.sbjv.2.sg" ,
"prs.sbjv.3.pl" : "prs.act.sbjv.3.pl" ,
"prs.sbjv.3.sg" : "prs.act.sbjv.3.sg" ,
}

for i in UD_features.index:
    if UD_features.loc[i,"cell_mapped"] in postHoc_corr:
        UD_features.loc[i,"cell_mapped"] = postHoc_corr[UD_features.loc[i,"cell_mapped"]]

finding remaining problems

In [23]:
latinflexi_cells = pd.read_csv("../LatInfLexi-cells.csv", index_col=0)

In [24]:
latinflexi_cells

,ud,unimorph,cell_romance_aligned,cell_LatInfLexi_v1,POS,frequency,frequency_Antiquitas,frequency_AetasPatrum,frequency_MediumAeuum,frequency_RecentiorLatinitas
cell_id,,,,,,,,,,
prs.act.ind.1.sg,VerbForm=Fin|Mood=Ind|Tense=Pres|Aspect=Imp|Vo...,V;FIN;ACT;PRS;IPFV;IND;1;SG,PRS-IND~1SG,VERB:Fin+Ind+Pres+-+Act+1+Sing+-+-,verb,739362,91759,249823,369678,28102
prs.act.ind.2.sg,VerbForm=Fin|Mood=Ind|Tense=Pres|Aspect=Imp|Vo...,V;FIN;ACT;PRS;IPFV;IND;2;SG,PRS-IND~2SG,VERB:Fin+Ind+Pres+-+Act+2+Sing+-+-,verb,506527,67863,197762,223077,17825
prs.act.ind.3.sg,VerbForm=Fin|Mood=Ind|Tense=Pres|Aspect=Imp|Vo...,V;FIN;ACT;PRS;IPFV;IND;3;SG,PRS-IND~3SG,VERB:Fin+Ind+Pres+-+Act+3+Sing+-+-,verb,2900100,191845,926928,1699035,82292
prs.act.ind.1.pl,VerbForm=Fin|Mood=Ind|Tense=Pres|Aspect=Imp|Vo...,V;FIN;ACT;PRS;IPFV;IND;1;PL,PRS-IND~1PL,VERB:Fin+Ind+Pres+-+Act+1+Plur+-+-,verb,184046,10467,84917,80393,8269
prs.act.ind.2.pl,VerbForm=Fin|Mood=Ind|Tense=Pres|Aspect=Imp|Vo...,V;FIN;ACT;PRS;IPFV;IND;2;PL,PRS-IND~2PL,VERB:Fin+Ind+Pres+-+Act+2+Plur+-+-,verb,103442,9710,43734,48116,1882
...,...,...,...,...,...,...,...,...,...,...
gen.pl,Case=Gen|Number=Plur,N;GEN;PL,NaN,NOUN:Gen+Plur,noun,518465,56573,189629,250017,22246
dat.pl,Case=Dat|Number=Plur,N;DAT;PL,NaN,NOUN:Dat+Plur,noun,835283,115180,310927,382000,27176
acc.pl,Case=Acc|Number=Plur,N;ACC;PL,NaN,NOUN:Acc+Plur,noun,1565479,216650,557840,734860,56129
voc.pl,Case=Voc|Number=Plur,N;VOC;PL,NaN,NOUN:Voc+Plur,noun,2113371,236521,758001,1044528,74321
abl.pl,Case=Abl|Number=Plur,N;ABL;PL,NaN,NOUN:Abl+Plur,noun,835283,115180,310927,382000,27176

In [25]:
cell_ls = [ i for i in latinflexi_cells.index.unique() ]

In [26]:
problem_ls = list()
for i in UD_features["cell_mapped"].unique():
    #print(i)
    if "/" not in i and i not in cell_ls:
        problem_ls.append(i)
problem_ls

['fut.sbjv.3.sg',
 'fut.sbjv.3.pl',
 'fut.sbjv.2.sg',
 'fut.sbjv.1.sg',
 'prf.pass.ptcp.m',
 'prf.pass.sbjv.1.sg',
 'prf.pass.ptcp.acc.f',
 '',
 'nanProsp.act.ptcp.acc.???',
 'fut.act.sbjv.3.sg',
 'prs.ptcp.sg',
 'prf.pass.ind.3.sg',
 'prf.pass.ptcp.f',
 'prs.act.ind.2',
 'prf.pass.ptcp.acc.m',
 'prf.pass.ptcp.acc.n',
 'acc.m.pl',
 'prf.pass.ptcp.nom.sg',
 'sg',
 'prf.act.ptcp.nom.m.sg',
 'nanProsp.act.ptcp.acc.sg???',
 'prf.pass.ind.1.sg',
 'nom.m.pl',
 'prf.pass.inf.acc.f.sg',
 'nom.m.sg',
 'fut.sbjv.1.pl',
 'pprf.pass.sbjv.3.pl',
 'prf.pass.ptcp.n.sg',
 'prf.pass.ptcp.m.sg',
 'prf.pass.ptcp',
 'prs.act.ind.3',
 'prs.ptcp.pl',
 'fprf.pass.ind.2.sg',
 'prf.pass.sbjv.2.sg',
 'prs.act.imp.3.sg',
 'fut.act.ptcp.acc.pl',
 'fut.pass.ptcp.acc.f.sg',
 'act.sg',
 'pprf.pass.sbjv.3.sg',
 'prf.pass.ptcp.m.pl',
 'fut.act.ptcp.acc',
 'fprf.pass.ind.3.sg',
 'fut.act.ptcp.acc.sg',
 'pprf.pass.sbjv.1.sg',
 'pprf.pass.ind.3.sg',
 'fut.act.ptcp.acc.m',
 'prs.act.ind.1',
 'prf.pass.ptcp.nom.pl',
 'prf.pass.sbjv.3.sg',
 'prf.act.ptcp.nom.f.sg']

In [27]:
UD_paralex_mapping = UD_features[["UD_features","cell_mapped"]]

In [28]:
UD_paralex_mapping = UD_paralex_mapping.set_index("UD_features")

## Mapping cells of nominal/adjectival forms in LatInfLexi to a notation underspecified for gender (to match the one in LASLA)

In [29]:
mapping_underspecified_cells = pd.read_csv("mapping_underspecified_cells.csv",sep="\t")
mapping_underspecified_cells

,cell_underspecified,cells
0,prf.pass.ptcp.acc.m/n.sg,"prf.pass.ptcp.acc.m.sg,prf.pass.ptcp.acc.n.sg"
1,fut.act.ptcp.acc.m/n.sg,"fut.act.ptcp.acc.m.sg,fut.act.ptcp.acc.n.sg"
2,prf.pass.ptcp.abl.m/n.sg,"prf.pass.ptcp.abl.m.sg,prf.pass.ptcp.abl.n.sg"
3,prf.pass.ptcp.abl.f/m/n.pl,"prf.pass.ptcp.abl.f.pl,prf.pass.ptcp.abl.m.pl,..."
4,fut.act.ptcp.acc.m/n.sg,"fut.act.ptcp.acc.m.sg,fut.act.ptcp.acc.n.sg"
...,...,...
241,prf.pass.ptcp.nom.m/n.sg,"prf.pass.ptcp.nom.m.sg,prf.pass.ptcp.nom.n.sg"
242,fut.act.ptcp.abl.m/n.sg,"fut.act.ptcp.abl.m.sg,fut.act.ptcp.abl.n.sg"
243,fut.pass.ptcp.acc.m/n.sg,"fut.pass.ptcp.acc.m.sg,fut.pass.ptcp.acc.n.sg"
244,prf.pass.ptcp.nom.m/n.pl,"prf.pass.ptcp.nom.m.pl,prf.pass.ptcp.nom.n.pl"
245,prs.act.ptcp.f/m/n,"prs.act.ptcp.f,prs.act.ptcp.m,prs.act.ptcp.n"

In [30]:
for col in mapping_underspecified_cells:
    if col not in ["cell_underspecified","cells"]:
        mapping_underspecified_cells = mapping_underspecified_cells.drop(columns = col)

In [31]:
mapping_underspecified_cells = mapping_underspecified_cells.drop_duplicates().reset_index(drop=True)

In [32]:
mapping_underspecified_cells

,cell_underspecified,cells
0,prf.pass.ptcp.acc.m/n.sg,"prf.pass.ptcp.acc.m.sg,prf.pass.ptcp.acc.n.sg"
1,fut.act.ptcp.acc.m/n.sg,"fut.act.ptcp.acc.m.sg,fut.act.ptcp.acc.n.sg"
2,prf.pass.ptcp.abl.m/n.sg,"prf.pass.ptcp.abl.m.sg,prf.pass.ptcp.abl.n.sg"
3,prf.pass.ptcp.abl.f/m/n.pl,"prf.pass.ptcp.abl.f.pl,prf.pass.ptcp.abl.m.pl,..."
4,prs.act.ptcp.nom.f/m/n.sg,"prs.act.ptcp.nom.f.sg,prs.act.ptcp.nom.m.sg,pr..."
...,...,...
58,prf.pass.ptcp.dat.f/m/n.sg,"prf.pass.ptcp.dat.f.sg,prf.pass.ptcp.dat.m.sg,..."
59,prs.pass.ptcp.dat.f/m/n.sg,"prs.pass.ptcp.dat.f.sg,prs.pass.ptcp.dat.m.sg,..."
60,prs.act.ptcp.abl.f/m.sg,"prs.act.ptcp.abl.f.sg,prs.act.ptcp.abl.m.sg"
61,fut.ptcp.gen.m/n.sg,"fut.ptcp.gen.m.sg,fut.ptcp.gen.n.sg"
62,fut.pass.ptcp.acc.m/n.sg,"fut.pass.ptcp.acc.m.sg,fut.pass.ptcp.acc.n.sg"

In [33]:
for i in mapping_underspecified_cells.index:
    print("index",i,type(i))
    compatible_cells = mapping_underspecified_cells.loc[i,"cells"].split(",")
    print(len(compatible_cells))
    for n in range(len(compatible_cells)):
        print(compatible_cells[n])
        newIndex = len(mapping_underspecified_cells)
        print("newIndex",newIndex)
        mapping_underspecified_cells.loc[newIndex,"cell"] = compatible_cells[n]
        mapping_underspecified_cells.loc[newIndex,"cell_underspecified"] = mapping_underspecified_cells.loc[i,"cell_underspecified"]

index 0 <class 'int'>
2
prf.pass.ptcp.acc.m.sg
newIndex 63
prf.pass.ptcp.acc.n.sg
newIndex 64
index 1 <class 'int'>
2
fut.act.ptcp.acc.m.sg
newIndex 65
fut.act.ptcp.acc.n.sg
newIndex 66
index 2 <class 'int'>
2
prf.pass.ptcp.abl.m.sg
newIndex 67
prf.pass.ptcp.abl.n.sg
newIndex 68
index 3 <class 'int'>
3
prf.pass.ptcp.abl.f.pl
newIndex 69
prf.pass.ptcp.abl.m.pl
newIndex 70
prf.pass.ptcp.abl.n.pl
newIndex 71
index 4 <class 'int'>
3
prs.act.ptcp.nom.f.sg
newIndex 72
prs.act.ptcp.nom.m.sg
newIndex 73
prs.act.ptcp.nom.n.sg
newIndex 74
index 5 <class 'int'>
3
prf.pass.ptcp.dat.f.pl
newIndex 75
prf.pass.ptcp.dat.m.pl
newIndex 76
prf.pass.ptcp.dat.n.pl
newIndex 77
index 6 <class 'int'>
2
prs.act.ptcp.acc.f.sg
newIndex 78
prs.act.ptcp.acc.m.sg
newIndex 79
index 7 <class 'int'>
3
prs.act.ptcp.abl.f.sg
newIndex 80
prs.act.ptcp.abl.m.sg
newIndex 81
prs.act.ptcp.abl.n.sg
newIndex 82
index 8 <class 'int'>
2
gdv.acc.m.sg
newIndex 83
gdv.acc.n.sg
newIndex 84
index 9 <class 'int'>
3
gdv.abl.f.pl
newIndex 85
gdv.abl.m.pl
newIndex 86
gdv.abl.n.pl
newIndex 87
index 10 <class 'int'>
3
prs.act.ptcp.dat.f.sg
newIndex 88
prs.act.ptcp.dat.m.sg
newIndex 89
prs.act.ptcp.dat.n.sg
newIndex 90
index 11 <class 'int'>
3
prs.act.ptcp.gen.f.sg
newIndex 91
prs.act.ptcp.gen.m.sg
newIndex 92
prs.act.ptcp.gen.n.sg
newIndex 93
index 12 <class 'int'>
2
prs.act.ptcp.nom.f.pl
newIndex 94
prs.act.ptcp.nom.m.pl
newIndex 95
index 13 <class 'int'>
2
prs.act.ptcp.acc.f.pl
newIndex 96
prs.act.ptcp.acc.m.pl
newIndex 97
index 14 <class 'int'>
3
prs.act.ptcp.gen.f.pl
newIndex 98
prs.act.ptcp.gen.m.pl
newIndex 99
prs.act.ptcp.gen.n.pl
newIndex 100
index 15 <class 'int'>
3
prs.act.ptcp.dat.f.pl
newIndex 101
prs.act.ptcp.dat.m.pl
newIndex 102
prs.act.ptcp.dat.n.pl
newIndex 103
index 16 <class 'int'>
3
prs.act.ptcp.abl.f.pl
newIndex 104
prs.act.ptcp.abl.m.pl
newIndex 105
prs.act.ptcp.abl.n.pl
newIndex 106
index 17 <class 'int'>
2
gdv.gen.m.sg
newIndex 107
gdv.gen.n.sg
newIndex 108
index 18 <class 'int'>
2
prf.pass.ptcp.dat.m.sg
newIndex 109
prf.pass.ptcp.dat.n.sg
newIndex 110
index 19 <class 'int'>
2
prf.pass.ptcp.gen.m.sg
newIndex 111
prf.pass.ptcp.gen.n.sg
newIndex 112
index 20 <class 'int'>
2
prf.pass.ptcp.gen.m.pl
newIndex 113
prf.pass.ptcp.gen.n.pl
newIndex 114
index 21 <class 'int'>
2
fut.act.ptcp.gen.m.sg
newIndex 115
fut.act.ptcp.gen.n.sg
newIndex 116
index 22 <class 'int'>
2
gdv.abl.m.sg
newIndex 117
gdv.abl.n.sg
newIndex 118
index 23 <class 'int'>
2
fut.act.ptcp.dat.m.sg
newIndex 119
fut.act.ptcp.dat.n.sg
newIndex 120
index 24 <class 'int'>
2
fut.ptcp.acc.m.sg
newIndex 121
fut.ptcp.acc.n.sg
newIndex 122
index 25 <class 'int'>
3
gdv.dat.f.pl
newIndex 123
gdv.dat.m.pl
newIndex 124
gdv.dat.n.pl
newIndex 125
index 26 <class 'int'>
2
gdv.dat.m.sg
newIndex 126
gdv.dat.n.sg
newIndex 127
index 27 <class 'int'>
2
gdv.nom.m.sg
newIndex 128
gdv.nom.n.sg
newIndex 129
index 28 <class 'int'>
2
gdv.gen.m.pl
newIndex 130
gdv.gen.n.pl
newIndex 131
index 29 <class 'int'>
2
prf.pass.inf.acc.m.sg
newIndex 132
prf.pass.inf.acc.n.sg
newIndex 133
index 30 <class 'int'>
3
fut.act.ptcp.dat.f.pl
newIndex 134
fut.act.ptcp.dat.m.pl
newIndex 135
fut.act.ptcp.dat.n.pl
newIndex 136
index 31 <class 'int'>
2
prf.pass.ptcp.voc.m.pl
newIndex 137
prf.pass.ptcp.voc.n.pl
newIndex 138
index 32 <class 'int'>
2
prf.pass.ptcp.nom.m.sg
newIndex 139
prf.pass.ptcp.nom.n.sg
newIndex 140
index 33 <class 'int'>
2
prf.pass.ptcp.acc.m
newIndex 141
prf.pass.ptcp.acc.n
newIndex 142
index 34 <class 'int'>
2
fut.act.ptcp.gen.m.pl
newIndex 143
fut.act.ptcp.gen.n.pl
newIndex 144
index 35 <class 'int'>
3
prs.act.ptcp.voc.f.sg
newIndex 145
prs.act.ptcp.voc.m.sg
newIndex 146
prs.act.ptcp.voc.n.sg
newIndex 147
index 36 <class 'int'>
3
prs.act.ptcp.acc.f.pl
newIndex 148
prs.act.ptcp.acc.m.pl
newIndex 149
prs.act.ptcp.acc.n.pl
newIndex 150
index 37 <class 'int'>
2
prf.pass.ptcp.nom.m.pl
newIndex 151
prf.pass.ptcp.nom.n.pl
newIndex 152
index 38 <class 'int'>
2
fut.act.ptcp.abl.m.sg
newIndex 153
fut.act.ptcp.abl.n.sg
newIndex 154
index 39 <class 'int'>
3
prf.pass.ptcp.abl.f.sg
newIndex 155
prf.pass.ptcp.abl.m.sg
newIndex 156
prf.pass.ptcp.abl.n.sg
newIndex 157
index 40 <class 'int'>
3
dat.f.pl
newIndex 158
dat.m.pl
newIndex 159
dat.n.pl
newIndex 160
index 41 <class 'int'>
3
abl.f.pl
newIndex 161
abl.m.pl
newIndex 162
abl.n.pl
newIndex 163
index 42 <class 'int'>
2
prs.act.ptcp.voc.f.pl
newIndex 164
prs.act.ptcp.voc.m.pl
newIndex 165
index 43 <class 'int'>
2
gen.m.pl
newIndex 166
gen.n.pl
newIndex 167
index 44 <class 'int'>
3
fut.act.ptcp.abl.f.pl
newIndex 168
fut.act.ptcp.abl.m.pl
newIndex 169
fut.act.ptcp.abl.n.pl
newIndex 170
index 45 <class 'int'>
2
prf.pass.ptcp.acc.m.pl
newIndex 171
prf.pass.ptcp.acc.n.pl
newIndex 172
index 46 <class 'int'>
3
prf.act.ptcp.abl.f.sg
newIndex 173
prf.act.ptcp.abl.m.sg
newIndex 174
prf.act.ptcp.abl.n.sg
newIndex 175
index 47 <class 'int'>
2
prs.act.ptcp.f
newIndex 176
prs.act.ptcp.m
newIndex 177
index 48 <class 'int'>
2
fut.ptcp.abl.m.sg
newIndex 178
fut.ptcp.abl.n.sg
newIndex 179
index 49 <class 'int'>
3
prs.act.ptcp.f
newIndex 180
prs.act.ptcp.m
newIndex 181
prs.act.ptcp.n
newIndex 182
index 50 <class 'int'>
3
prs.act.ptcp.acc.f.sg
newIndex 183
prs.act.ptcp.acc.m.sg
newIndex 184
prs.act.ptcp.acc.n.sg
newIndex 185
index 51 <class 'int'>
2
prs.act.ptcp.gen.f.sg
newIndex 186
prs.act.ptcp.gen.m.sg
newIndex 187
index 52 <class 'int'>
2
fut.ptcp.dat.m.sg
newIndex 188
fut.ptcp.dat.n.sg
newIndex 189
index 53 <class 'int'>
2
fut.act.ptcp.acc.m
newIndex 190
fut.act.ptcp.acc.n
newIndex 191
index 54 <class 'int'>
3
prf.pass.ptcp.gen.f.sg
newIndex 192
prf.pass.ptcp.gen.m.sg
newIndex 193
prf.pass.ptcp.gen.n.sg
newIndex 194
index 55 <class 'int'>
3
fut.ptcp.abl.f.pl
newIndex 195
fut.ptcp.abl.m.pl
newIndex 196
fut.ptcp.abl.n.pl
newIndex 197
index 56 <class 'int'>
2
prs.act.ptcp.nom.f.sg
newIndex 198
prs.act.ptcp.nom.m.sg
newIndex 199
index 57 <class 'int'>
2
prf.pass.ptcp.abl.m.pl
newIndex 200
prf.pass.ptcp.abl.n.pl
newIndex 201
index 58 <class 'int'>
3
prf.pass.ptcp.dat.f.sg
newIndex 202
prf.pass.ptcp.dat.m.sg
newIndex 203
prf.pass.ptcp.dat.n.sg
newIndex 204
index 59 <class 'int'>
3
prs.pass.ptcp.dat.f.sg
newIndex 205
prs.pass.ptcp.dat.m.sg
newIndex 206
prs.pass.ptcp.dat.n.sg
newIndex 207
index 60 <class 'int'>
2
prs.act.ptcp.abl.f.sg
newIndex 208
prs.act.ptcp.abl.m.sg
newIndex 209
index 61 <class 'int'>
2
fut.ptcp.gen.m.sg
newIndex 210
fut.ptcp.gen.n.sg
newIndex 211
index 62 <class 'int'>
2
fut.pass.ptcp.acc.m.sg
newIndex 212
fut.pass.ptcp.acc.n.sg
newIndex 213

C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1835049281.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'prf.pass.ptcp.acc.m.sg' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  mapping_underspecified_cells.loc[newIndex,"cell"] = compatible_cells[n]

In [34]:
mapping_underspecified_cells = mapping_underspecified_cells.dropna(subset=["cell"]).drop(columns = "cells").set_index("cell")

In [35]:
mapping_underspecified_cells

                             cell_underspecified
cell
prf.pass.ptcp.acc.m.sg  prf.pass.ptcp.acc.m/n.sg
prf.pass.ptcp.acc.n.sg  prf.pass.ptcp.acc.m/n.sg
fut.act.ptcp.acc.m.sg    fut.act.ptcp.acc.m/n.sg
fut.act.ptcp.acc.n.sg    fut.act.ptcp.acc.m/n.sg
prf.pass.ptcp.abl.m.sg  prf.pass.ptcp.abl.m/n.sg
...                                          ...
prs.act.ptcp.abl.m.sg    prs.act.ptcp.abl.f/m.sg
fut.ptcp.gen.m.sg            fut.ptcp.gen.m/n.sg
fut.ptcp.gen.n.sg            fut.ptcp.gen.m/n.sg
fut.pass.ptcp.acc.m.sg  fut.pass.ptcp.acc.m/n.sg
fut.pass.ptcp.acc.n.sg  fut.pass.ptcp.acc.m/n.sg

[151 rows x 1 columns]

finding cells that map to multiple underspecified cells (that are problematic and in most cases due to errors/inconsistencies in LASLA)

In [36]:
cells = list()
cells_toBeChecked = dict()
for i in mapping_underspecified_cells.index:
    if i not in cells:
        cells.append(i)
    else:
        #print(i,mapping_underspecified_cells.loc[i,"cell_underspecified"])
        amb = list()
        for und in mapping_underspecified_cells.loc[i,"cell_underspecified"]:
            amb.append(und)
        cells_toBeChecked[i] = amb

In [37]:
cells_toBeChecked

{'prs.act.ptcp.acc.f.pl': ['prs.act.ptcp.acc.f/m.pl',
  'prs.act.ptcp.acc.f/m/n.pl'],
 'prs.act.ptcp.acc.m.pl': ['prs.act.ptcp.acc.f/m.pl',
  'prs.act.ptcp.acc.f/m/n.pl'],
 'prf.pass.ptcp.abl.m.sg': ['prf.pass.ptcp.abl.m/n.sg',
  'prf.pass.ptcp.abl.f/m/n.sg'],
 'prf.pass.ptcp.abl.n.sg': ['prf.pass.ptcp.abl.m/n.sg',
  'prf.pass.ptcp.abl.f/m/n.sg'],
 'prs.act.ptcp.f': ['prs.act.ptcp.f/m', 'prs.act.ptcp.f/m/n'],
 'prs.act.ptcp.m': ['prs.act.ptcp.f/m', 'prs.act.ptcp.f/m/n'],
 'prs.act.ptcp.acc.f.sg': ['prs.act.ptcp.acc.f/m.sg',
  'prs.act.ptcp.acc.f/m/n.sg'],
 'prs.act.ptcp.acc.m.sg': ['prs.act.ptcp.acc.f/m.sg',
  'prs.act.ptcp.acc.f/m/n.sg'],
 'prs.act.ptcp.gen.f.sg': ['prs.act.ptcp.gen.f/m/n.sg',
  'prs.act.ptcp.gen.f/m.sg'],
 'prs.act.ptcp.gen.m.sg': ['prs.act.ptcp.gen.f/m/n.sg',
  'prs.act.ptcp.gen.f/m.sg'],
 'prf.pass.ptcp.gen.m.sg': ['prf.pass.ptcp.gen.m/n.sg',
  'prf.pass.ptcp.gen.f/m/n.sg'],
 'prf.pass.ptcp.gen.n.sg': ['prf.pass.ptcp.gen.m/n.sg',
  'prf.pass.ptcp.gen.f/m/n.sg'],
 'prs.act.ptcp.nom.f.sg': ['prs.act.ptcp.nom.f/m/n.sg',
  'prs.act.ptcp.nom.f/m.sg'],
 'prs.act.ptcp.nom.m.sg': ['prs.act.ptcp.nom.f/m/n.sg',
  'prs.act.ptcp.nom.f/m.sg'],
 'prf.pass.ptcp.abl.m.pl': ['prf.pass.ptcp.abl.f/m/n.pl',
  'prf.pass.ptcp.abl.m/n.pl'],
 'prf.pass.ptcp.abl.n.pl': ['prf.pass.ptcp.abl.f/m/n.pl',
  'prf.pass.ptcp.abl.m/n.pl'],
 'prf.pass.ptcp.dat.m.sg': ['prf.pass.ptcp.dat.m/n.sg',
  'prf.pass.ptcp.dat.f/m/n.sg'],
 'prf.pass.ptcp.dat.n.sg': ['prf.pass.ptcp.dat.m/n.sg',
  'prf.pass.ptcp.dat.f/m/n.sg'],
 'prs.act.ptcp.abl.f.sg': ['prs.act.ptcp.abl.f/m/n.sg',
  'prs.act.ptcp.abl.f/m.sg'],
 'prs.act.ptcp.abl.m.sg': ['prs.act.ptcp.abl.f/m/n.sg',
  'prs.act.ptcp.abl.f/m.sg']}

manual disambiguation of problematic cases

In [38]:
manual_disambiguation = {'prs.act.ptcp.acc.f.pl': 'prs.act.ptcp.acc.f/m.pl' ,
 'prs.act.ptcp.acc.m.pl': 'prs.act.ptcp.acc.f/m.pl' ,
 'prf.pass.ptcp.abl.m.sg': 'prf.pass.ptcp.abl.m/n.sg',
 'prf.pass.ptcp.abl.n.sg': 'prf.pass.ptcp.abl.m/n.sg',
 'prs.act.ptcp.f': '',
 'prs.act.ptcp.m': '',
 'prs.act.ptcp.acc.f.sg': 'prs.act.ptcp.acc.f/m.sg',
 'prs.act.ptcp.acc.m.sg': 'prs.act.ptcp.acc.f/m.sg',
 'prs.act.ptcp.gen.f.sg': 'prs.act.ptcp.gen.f/m/n.sg',
 'prs.act.ptcp.gen.m.sg': 'prs.act.ptcp.gen.f/m/n.sg',
 'prf.pass.ptcp.gen.m.sg': 'prf.pass.ptcp.gen.m/n.sg',
 'prf.pass.ptcp.gen.n.sg': 'prf.pass.ptcp.gen.m/n.sg',
 'prs.act.ptcp.nom.f.sg': 'prs.act.ptcp.nom.f/m/n.sg',
 'prs.act.ptcp.nom.m.sg': 'prs.act.ptcp.nom.f/m/n.sg',
 'prf.pass.ptcp.abl.m.pl': 'prf.pass.ptcp.abl.f/m/n.pl',
 'prf.pass.ptcp.abl.n.pl': 'prf.pass.ptcp.abl.f/m/n.pl',
 'prf.pass.ptcp.dat.m.sg': 'prf.pass.ptcp.dat.m/n.sg',
 'prf.pass.ptcp.dat.n.sg': 'prf.pass.ptcp.dat.m/n.sg',
 'prs.act.ptcp.abl.f.sg': 'prs.act.ptcp.abl.f/m/n.sg',
 'prs.act.ptcp.abl.m.sg': 'prs.act.ptcp.abl.f/m/n.sg'}

obtaining mapping dictionary

In [39]:
mapping_dict = dict()

for i in mapping_underspecified_cells.index:
    # manually added list of cells that should not be mapped to underspecified cell
    if i not in [ 'prf.pass.ptcp.nom.m.sg', 'prf.pass.ptcp.nom.n.sg', 'prf.pass.ptcp.nom.m.pl', 'prf.pass.ptcp.nom.n.pl', 'prf.pass.ptcp.acc.m.pl', 'prf.pass.ptcp.acc.n.pl', 'gdv.nom.m.sg', 'gdv.nom.n.sg']:
        if i in cells_toBeChecked:
            mapping_dict[i] = manual_disambiguation[i]
        else:
            mapping_dict[i] = mapping_underspecified_cells.loc[i,"cell_underspecified"]

mapping_dict

{'prf.pass.ptcp.acc.m.sg': 'prf.pass.ptcp.acc.m/n.sg',
 'prf.pass.ptcp.acc.n.sg': 'prf.pass.ptcp.acc.m/n.sg',
 'fut.act.ptcp.acc.m.sg': 'fut.act.ptcp.acc.m/n.sg',
 'fut.act.ptcp.acc.n.sg': 'fut.act.ptcp.acc.m/n.sg',
 'prf.pass.ptcp.abl.m.sg': 'prf.pass.ptcp.abl.m/n.sg',
 'prf.pass.ptcp.abl.n.sg': 'prf.pass.ptcp.abl.m/n.sg',
 'prf.pass.ptcp.abl.f.pl': 'prf.pass.ptcp.abl.f/m/n.pl',
 'prf.pass.ptcp.abl.m.pl': 'prf.pass.ptcp.abl.f/m/n.pl',
 'prf.pass.ptcp.abl.n.pl': 'prf.pass.ptcp.abl.f/m/n.pl',
 'prs.act.ptcp.nom.f.sg': 'prs.act.ptcp.nom.f/m/n.sg',
 'prs.act.ptcp.nom.m.sg': 'prs.act.ptcp.nom.f/m/n.sg',
 'prs.act.ptcp.nom.n.sg': 'prs.act.ptcp.nom.f/m/n.sg',
 'prf.pass.ptcp.dat.f.pl': 'prf.pass.ptcp.dat.f/m/n.pl',
 'prf.pass.ptcp.dat.m.pl': 'prf.pass.ptcp.dat.f/m/n.pl',
 'prf.pass.ptcp.dat.n.pl': 'prf.pass.ptcp.dat.f/m/n.pl',
 'prs.act.ptcp.acc.f.sg': 'prs.act.ptcp.acc.f/m.sg',
 'prs.act.ptcp.acc.m.sg': 'prs.act.ptcp.acc.f/m.sg',
 'prs.act.ptcp.abl.f.sg': 'prs.act.ptcp.abl.f/m/n.sg',
 'prs.act.ptcp.abl.m.sg': 'prs.act.ptcp.abl.f/m/n.sg',
 'prs.act.ptcp.abl.n.sg': 'prs.act.ptcp.abl.f/m/n.sg',
 'gdv.acc.m.sg': 'gdv.acc.m/n.sg',
 'gdv.acc.n.sg': 'gdv.acc.m/n.sg',
 'gdv.abl.f.pl': 'gdv.abl.f/m/n.pl',
 'gdv.abl.m.pl': 'gdv.abl.f/m/n.pl',
 'gdv.abl.n.pl': 'gdv.abl.f/m/n.pl',
 'prs.act.ptcp.dat.f.sg': 'prs.act.ptcp.dat.f/m/n.sg',
 'prs.act.ptcp.dat.m.sg': 'prs.act.ptcp.dat.f/m/n.sg',
 'prs.act.ptcp.dat.n.sg': 'prs.act.ptcp.dat.f/m/n.sg',
 'prs.act.ptcp.gen.f.sg': 'prs.act.ptcp.gen.f/m/n.sg',
 'prs.act.ptcp.gen.m.sg': 'prs.act.ptcp.gen.f/m/n.sg',
 'prs.act.ptcp.gen.n.sg': 'prs.act.ptcp.gen.f/m/n.sg',
 'prs.act.ptcp.nom.f.pl': 'prs.act.ptcp.nom.f/m.pl',
 'prs.act.ptcp.nom.m.pl': 'prs.act.ptcp.nom.f/m.pl',
 'prs.act.ptcp.acc.f.pl': 'prs.act.ptcp.acc.f/m.pl',
 'prs.act.ptcp.acc.m.pl': 'prs.act.ptcp.acc.f/m.pl',
 'prs.act.ptcp.gen.f.pl': 'prs.act.ptcp.gen.f/m/n.pl',
 'prs.act.ptcp.gen.m.pl': 'prs.act.ptcp.gen.f/m/n.pl',
 'prs.act.ptcp.gen.n.pl': 'prs.act.ptcp.gen.f/m/n.pl',
 'prs.act.ptcp.dat.f.pl': 'prs.act.ptcp.dat.f/m/n.pl',
 'prs.act.ptcp.dat.m.pl': 'prs.act.ptcp.dat.f/m/n.pl',
 'prs.act.ptcp.dat.n.pl': 'prs.act.ptcp.dat.f/m/n.pl',
 'prs.act.ptcp.abl.f.pl': 'prs.act.ptcp.abl.f/m/n.pl',
 'prs.act.ptcp.abl.m.pl': 'prs.act.ptcp.abl.f/m/n.pl',
 'prs.act.ptcp.abl.n.pl': 'prs.act.ptcp.abl.f/m/n.pl',
 'gdv.gen.m.sg': 'gdv.gen.m/n.sg',
 'gdv.gen.n.sg': 'gdv.gen.m/n.sg',
 'prf.pass.ptcp.dat.m.sg': 'prf.pass.ptcp.dat.m/n.sg',
 'prf.pass.ptcp.dat.n.sg': 'prf.pass.ptcp.dat.m/n.sg',
 'prf.pass.ptcp.gen.m.sg': 'prf.pass.ptcp.gen.m/n.sg',
 'prf.pass.ptcp.gen.n.sg': 'prf.pass.ptcp.gen.m/n.sg',
 'prf.pass.ptcp.gen.m.pl': 'prf.pass.ptcp.gen.m/n.pl',
 'prf.pass.ptcp.gen.n.pl': 'prf.pass.ptcp.gen.m/n.pl',
 'fut.act.ptcp.gen.m.sg': 'fut.act.ptcp.gen.m/n.sg',
 'fut.act.ptcp.gen.n.sg': 'fut.act.ptcp.gen.m/n.sg',
 'gdv.abl.m.sg': 'gdv.abl.m/n.sg',
 'gdv.abl.n.sg': 'gdv.abl.m/n.sg',
 'fut.act.ptcp.dat.m.sg': 'fut.act.ptcp.dat.m/n.sg',
 'fut.act.ptcp.dat.n.sg': 'fut.act.ptcp.dat.m/n.sg',
 'fut.ptcp.acc.m.sg': 'fut.ptcp.acc.m/n.sg',
 'fut.ptcp.acc.n.sg': 'fut.ptcp.acc.m/n.sg',
 'gdv.dat.f.pl': 'gdv.dat.f/m/n.pl',
 'gdv.dat.m.pl': 'gdv.dat.f/m/n.pl',
 'gdv.dat.n.pl': 'gdv.dat.f/m/n.pl',
 'gdv.dat.m.sg': 'gdv.dat.m/n.sg',
 'gdv.dat.n.sg': 'gdv.dat.m/n.sg',
 'gdv.gen.m.pl': 'gdv.gen.m/n.pl',
 'gdv.gen.n.pl': 'gdv.gen.m/n.pl',
 'prf.pass.inf.acc.m.sg': 'prf.pass.inf.acc.m/n.sg',
 'prf.pass.inf.acc.n.sg': 'prf.pass.inf.acc.m/n.sg',
 'fut.act.ptcp.dat.f.pl': 'fut.act.ptcp.dat.f/m/n.pl',
 'fut.act.ptcp.dat.m.pl': 'fut.act.ptcp.dat.f/m/n.pl',
 'fut.act.ptcp.dat.n.pl': 'fut.act.ptcp.dat.f/m/n.pl',
 'prf.pass.ptcp.voc.m.pl': 'prf.pass.ptcp.voc.m/n.pl',
 'prf.pass.ptcp.voc.n.pl': 'prf.pass.ptcp.voc.m/n.pl',
 'prf.pass.ptcp.acc.m': 'prf.pass.ptcp.acc.m/n',
 'prf.pass.ptcp.acc.n': 'prf.pass.ptcp.acc.m/n',
 'fut.act.ptcp.gen.m.pl': 'fut.act.ptcp.gen.m/n.pl',
 'fut.act.ptcp.gen.n.pl': 'fut.act.ptcp.gen.m/n.pl',
 'prs.act.ptcp.voc.f.sg': 'prs.act.ptcp.voc.f/m/n.sg',
 'prs.act.ptcp.voc.m.sg': 'prs.act.ptcp.voc.f/m/n.sg',
 'prs.act.ptcp.voc.n.sg': 'prs.act.ptcp.voc.f/m/n.sg',
 'prs.act.ptcp.acc.n.pl': 'prs.act.ptcp.acc.f/m/n.pl',
 'fut.act.ptcp.abl.m.sg': 'fut.act.ptcp.abl.m/n.sg',
 'fut.act.ptcp.abl.n.sg': 'fut.act.ptcp.abl.m/n.sg',
 'prf.pass.ptcp.abl.f.sg': 'prf.pass.ptcp.abl.f/m/n.sg',
 'dat.f.pl': 'dat.f/m/n.pl',
 'dat.m.pl': 'dat.f/m/n.pl',
 'dat.n.pl': 'dat.f/m/n.pl',
 'abl.f.pl': 'abl.f/m/n.pl',
 'abl.m.pl': 'abl.f/m/n.pl',
 'abl.n.pl': 'abl.f/m/n.pl',
 'prs.act.ptcp.voc.f.pl': 'prs.act.ptcp.voc.f/m.pl',
 'prs.act.ptcp.voc.m.pl': 'prs.act.ptcp.voc.f/m.pl',
 'gen.m.pl': 'gen.m/n.pl',
 'gen.n.pl': 'gen.m/n.pl',
 'fut.act.ptcp.abl.f.pl': 'fut.act.ptcp.abl.f/m/n.pl',
 'fut.act.ptcp.abl.m.pl': 'fut.act.ptcp.abl.f/m/n.pl',
 'fut.act.ptcp.abl.n.pl': 'fut.act.ptcp.abl.f/m/n.pl',
 'prf.act.ptcp.abl.f.sg': 'prf.act.ptcp.abl.f/m/n.sg',
 'prf.act.ptcp.abl.m.sg': 'prf.act.ptcp.abl.f/m/n.sg',
 'prf.act.ptcp.abl.n.sg': 'prf.act.ptcp.abl.f/m/n.sg',
 'prs.act.ptcp.f': '',
 'prs.act.ptcp.m': '',
 'fut.ptcp.abl.m.sg': 'fut.ptcp.abl.m/n.sg',
 'fut.ptcp.abl.n.sg': 'fut.ptcp.abl.m/n.sg',
 'prs.act.ptcp.n': 'prs.act.ptcp.f/m/n',
 'prs.act.ptcp.acc.n.sg': 'prs.act.ptcp.acc.f/m/n.sg',
 'fut.ptcp.dat.m.sg': 'fut.ptcp.dat.m/n.sg',
 'fut.ptcp.dat.n.sg': 'fut.ptcp.dat.m/n.sg',
 'fut.act.ptcp.acc.m': 'fut.act.ptcp.acc.m/n',
 'fut.act.ptcp.acc.n': 'fut.act.ptcp.acc.m/n',
 'prf.pass.ptcp.gen.f.sg': 'prf.pass.ptcp.gen.f/m/n.sg',
 'fut.ptcp.abl.f.pl': 'fut.ptcp.abl.f/m/n.pl',
 'fut.ptcp.abl.m.pl': 'fut.ptcp.abl.f/m/n.pl',
 'fut.ptcp.abl.n.pl': 'fut.ptcp.abl.f/m/n.pl',
 'prf.pass.ptcp.dat.f.sg': 'prf.pass.ptcp.dat.f/m/n.sg',
 'prs.pass.ptcp.dat.f.sg': 'prs.pass.ptcp.dat.f/m/n.sg',
 'prs.pass.ptcp.dat.m.sg': 'prs.pass.ptcp.dat.f/m/n.sg',
 'prs.pass.ptcp.dat.n.sg': 'prs.pass.ptcp.dat.f/m/n.sg',
 'fut.ptcp.gen.m.sg': 'fut.ptcp.gen.m/n.sg',
 'fut.ptcp.gen.n.sg': 'fut.ptcp.gen.m/n.sg',
 'fut.pass.ptcp.acc.m.sg': 'fut.pass.ptcp.acc.m/n.sg',
 'fut.pass.ptcp.acc.n.sg': 'fut.pass.ptcp.acc.m/n.sg'}

In [40]:
def mapping_underspecified_cells_funct(cell):
    
    mapping = mapping_dict

    if cell in mapping:
        cell_underspecified = mapping[cell]
    else:
        cell_underspecified = cell
    
    return cell_underspecified

In [41]:
latinflexi_cells["cell_underspecified"] = latinflexi_cells.index.map(mapping_underspecified_cells_funct)

In [42]:
UD_paralex_mapping["cell_mapped_underspecified"] = UD_paralex_mapping["cell_mapped"].map(mapping_underspecified_cells_funct)

# Obtaining frequencies of cells
Using the mapping and the available information

In [43]:
for i in tqdm(lasla_tokens_UDset.index):
    UD_features = lasla_tokens_UDset.loc[i,"UD_features"]
    if UD_features in UD_paralex_mapping.index.unique():
        lasla_tokens_UDset.loc[i,"cell"] = UD_paralex_mapping.loc[lasla_tokens_UDset.loc[i,"UD_features"],"cell_mapped"]
        #lasla_tokens_UDset.loc[i,"cell_underspecified"] = UD_paralex_mapping.loc[lasla_tokens_UDset.loc[i,"UD_features"],"cell_mapped_underspecified"]
    else:
        print("PROBLEM",UD_features)

  0%|                                                                                       | 0/404654 [00:00<?, ?it/s]C:\Users\matteo.pellegrini\AppData\Local\Temp\ipykernel_6772\1153175885.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'prs.act.imp.2.sg' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  lasla_tokens_UDset.loc[i,"cell"] = UD_paralex_mapping.loc[lasla_tokens_UDset.loc[i,"UD_features"],"cell_mapped"]
100%|███████████████████████████████████████████████████████████████████████| 404654/404654 [00:34<00:00, 11836.06it/s]

In [44]:
lasla_cells_freq = lasla_tokens_UDset["cell"].value_counts().to_frame()

In [45]:
lasla_cells_freq

                          count
cell
prs.act.ind.3.sg          53771
prs.act.inf               40204
prf.act.ind.3.sg          24702
prs.act.ind.3.pl          17174
prs.act.sbjv.3.sg         13919
...                         ...
pprf.pass.sbjv.3.sg           1
fut.pass.ptcp.acc.m/n.sg      1
prf.act.ptcp.nom.f.sg         1
prf.pass.sbjv.3.sg            1
prs.act.ptcp.gen.f/m.sg       1

[301 rows x 1 columns]

In [46]:
mapping_underspecified_cells_bySpecifiedCell = mapping_underspecified_cells.reset_index().set_index("cell")
mapping_underspecified_cells_bySpecifiedCell

                             cell_underspecified
cell
prf.pass.ptcp.acc.m.sg  prf.pass.ptcp.acc.m/n.sg
prf.pass.ptcp.acc.n.sg  prf.pass.ptcp.acc.m/n.sg
fut.act.ptcp.acc.m.sg    fut.act.ptcp.acc.m/n.sg
fut.act.ptcp.acc.n.sg    fut.act.ptcp.acc.m/n.sg
prf.pass.ptcp.abl.m.sg  prf.pass.ptcp.abl.m/n.sg
...                                          ...
prs.act.ptcp.abl.m.sg    prs.act.ptcp.abl.f/m.sg
fut.ptcp.gen.m.sg            fut.ptcp.gen.m/n.sg
fut.ptcp.gen.n.sg            fut.ptcp.gen.m/n.sg
fut.pass.ptcp.acc.m.sg  fut.pass.ptcp.acc.m/n.sg
fut.pass.ptcp.acc.n.sg  fut.pass.ptcp.acc.m/n.sg

[151 rows x 1 columns]

In [47]:
for i in latinflexi_cells.index:
    if i in lasla_cells_freq.index:
        latinflexi_cells.loc[i,"frequency_lasla"] = lasla_cells_freq.loc[i,"count"]
    else:
        if i in mapping_dict:
            underspecified_cell = mapping_dict[i]
            nForms = underspecified_cell.count("/")+1
            latinflexi_cells.loc[i,"frequency_lasla"] = lasla_cells_freq.loc[underspecified_cell,"count"] / nForms

In [48]:
latinflexi_cells.to_csv("../LatInfLexi-cells.csv")